---
apiVersion: v1
kind: Service
metadata:
  name: liftbridge-headless
  labels:
    app: liftbridge
spec:
  selector:
    app: liftbridge
  clusterIP: "None"
  ports:
    - name: grpc
      protocol: TCP
      port: 9292
      targetPort: grpc
