---
apiVersion: v1
kind: Service
metadata:
  name: liftbridge
  labels:
    app: liftbridge
spec:
  selector:
    app: liftbridge
  ports:
    - name: grpc
      protocol: TCP
      port: 9292
      targetPort: grpc
